import Foundation

/// Filters out vague, pronominal, and meaningless nodes from extracted hypergraph events.
///
/// Despite prompt instructions, LLMs sometimes emit nodes like "we", "they", "it",
/// or vague terms like "material" or "method". This filter removes such nodes
/// as a post-processing step.
public enum NodeFilter {

    // MARK: - Stopword Lists

    /// Pronouns and demonstratives that should never be nodes.
    public static let pronouns: Set<String> = [
        // Personal pronouns
        "i", "we", "you", "he", "she", "it", "they",
        "me", "us", "him", "her", "them",
        "my", "our", "your", "his", "its", "their",
        "mine", "ours", "yours", "hers", "theirs",
        "myself", "ourselves", "yourself", "yourselves",
        "himself", "herself", "itself", "themselves",
        // Demonstratives
        "this", "that", "these", "those",
        // Relative/interrogative
        "who", "whom", "whose", "which", "what",
        // Indefinite
        "one", "ones", "someone", "anyone", "everyone", "no one",
        "something", "anything", "everything", "nothing",
        "some", "any", "all", "none", "both", "each", "other", "another",
    ]

    /// Vague nouns that are too generic to be meaningful nodes.
    public static let vagueNouns: Set<String> = [
        // Generic terms from the prompt
        "material", "materials",
        "material formulation", "formulation", "formulations",
        "solution", "solutions",
        "sample", "samples",
        "device", "devices",
        "method", "methods",
        "technique", "techniques",
        "approach", "approaches",
        "process", "processes",
        "system", "systems",
        "structure", "structures",
        "polymer", "polymers",
        "composite", "composites",
        "matrix", "matrices",
        "property", "properties",
        // Additional vague terms
        "thing", "things",
        "stuff",
        "result", "results",
        "study", "studies",
        "research",
        "work",
        "paper",
        "article",
        "experiment", "experiments",
        "analysis",
        "data",
        "finding", "findings",
        "observation", "observations",
        "example", "examples",
        "case", "cases",
        "factor", "factors",
        "aspect", "aspects",
        "feature", "features",
        "element", "elements",
        "component", "components",
        "part", "parts",
        "piece", "pieces",
        "item", "items",
        "object", "objects",
        "entity", "entities",
        "instance", "instances",
        "type", "types",
        "kind", "kinds",
        "sort", "sorts",
        "form", "forms",
        "way", "ways",
        "manner",
        "means",
        "effect", "effects",
        "impact", "impacts",
        "influence", "influences",
        "role", "roles",
        "purpose", "purposes",
        "function", "functions",
        "use", "uses",
        "application", "applications",
        "area", "areas",
        "field", "fields",
        "domain", "domains",
        "subject", "subjects",
        "topic", "topics",
        "issue", "issues",
        "problem", "problems",
        "question", "questions",
        "answer", "answers",
        "point", "points",
        "idea", "ideas",
        "concept", "concepts",
        "theory", "theories",
        "model", "models",
        "framework", "frameworks",
        "scheme", "schemes",
        "plan", "plans",
        "strategy", "strategies",
        "step", "steps",
        "stage", "stages",
        "phase", "phases",
        "level", "levels",
        "degree", "degrees",
        "extent",
        "amount", "amounts",
        "number", "numbers",
        "quantity", "quantities",
        "size", "sizes",
        "scale", "scales",
        "range", "ranges",
        "rate", "rates",
        "ratio", "ratios",
        "percentage", "percentages",
        "value", "values",
        "measure", "measures",
        "unit", "units",
        "parameter", "parameters",
        "variable", "variables",
        "condition", "conditions",
        "situation", "situations",
        "circumstance", "circumstances",
        "context", "contexts",
        "environment", "environments",
        "setting", "settings",
        "background", "backgrounds",
        "basis", "bases",
        "foundation", "foundations",
        "source", "sources",
        "origin", "origins",
        "cause", "causes",
        "reason", "reasons",
        "explanation", "explanations",
        "description", "descriptions",
        "account", "accounts",
        "report", "reports",
        "record", "records",
        "document", "documents",
        "information",
        "detail", "details",
        "fact", "facts",
        "evidence",
        "proof", "proofs",
        "support",
        "basis",
        "ground", "grounds",
        "criterion", "criteria",
        "standard", "standards",
        "norm", "norms",
        "rule", "rules",
        "principle", "principles",
        "law", "laws",
        "guideline", "guidelines",
        "requirement", "requirements",
        "specification", "specifications",
        "characteristic", "characteristics",
        "attribute", "attributes",
        "quality", "qualities",
        "nature",
        "essence",
        "substance", "substances",
        "content", "contents",
        "meaning", "meanings",
        "sense", "senses",
        "significance",
        "importance",
        "relevance",
        "connection", "connections",
        "relation", "relations",
        "relationship", "relationships",
        "link", "links",
        "bond", "bonds",
        "tie", "ties",
        "association", "associations",
        "correlation", "correlations",
        "interaction", "interactions",
        "combination", "combinations",
        "mixture", "mixtures",
        "blend", "blends",
        "compound", "compounds",
        "composition", "compositions",
        "configuration", "configurations",
        "arrangement", "arrangements",
        "organization", "organizations",
        "pattern", "patterns",
        "trend", "trends",
        "tendency", "tendencies",
        "behavior", "behaviors",
        "behaviour", "behaviours",
        "response", "responses",
        "reaction", "reactions",
        "change", "changes",
        "variation", "variations",
        "difference", "differences",
        "similarity", "similarities",
        "comparison", "comparisons",
        "contrast", "contrasts",
        "alternative", "alternatives",
        "option", "options",
        "choice", "choices",
        "possibility", "possibilities",
        "potential",
        "capability", "capabilities",
        "capacity", "capacities",
        "ability", "abilities",
        "skill", "skills",
        "knowledge",
        "understanding",
        "awareness",
        "insight", "insights",
        "perspective", "perspectives",
        "view", "views",
        "viewpoint", "viewpoints",
        "opinion", "opinions",
        "belief", "beliefs",
        "assumption", "assumptions",
        "hypothesis", "hypotheses",
        "prediction", "predictions",
        "expectation", "expectations",
        "goal", "goals",
        "objective", "objectives",
        "target", "targets",
        "aim", "aims",
        "intention", "intentions",
        "motivation", "motivations",
        "reason", "reasons",
        "advantage", "advantages",
        "benefit", "benefits",
        "disadvantage", "disadvantages",
        "drawback", "drawbacks",
        "limitation", "limitations",
        "constraint", "constraints",
        "restriction", "restrictions",
        "barrier", "barriers",
        "obstacle", "obstacles",
        "challenge", "challenges",
        "difficulty", "difficulties",
        "complexity", "complexities",
        "simplicity",
        "efficiency",
        "effectiveness",
        "performance",
        "success", "successes",
        "failure", "failures",
        "outcome", "outcomes",
        "conclusion", "conclusions",
        "summary", "summaries",
        "overview", "overviews",
        "introduction", "introductions",
        "beginning", "beginnings",
        "end", "ends",
        "start", "starts",
        "finish", "finishes",
        "completion",
        "progress",
        "development", "developments",
        "improvement", "improvements",
        "enhancement", "enhancements",
        "modification", "modifications",
        "adjustment", "adjustments",
        "correction", "corrections",
        "revision", "revisions",
        "update", "updates",
        "version", "versions",
        "edition", "editions",
        "copy", "copies",
        "sample",
        "specimen", "specimens",
        "portion", "portions",
        "section", "sections",
        "segment", "segments",
        "fragment", "fragments",
        "bit", "bits",
        "particle", "particles",
        "piece",
        "chunk", "chunks",
        "block", "blocks",
        "layer", "layers",
        "surface", "surfaces",
        "interface", "interfaces",
        "boundary", "boundaries",
        "edge", "edges",
        "side", "sides",
        "face", "faces",
        "top", "tops",
        "bottom", "bottoms",
        "front", "fronts",
        "back", "backs",
        "center", "centers",
        "centre", "centres",
        "middle", "middles",
        "interior", "interiors",
        "exterior", "exteriors",
        "inside", "insides",
        "outside", "outsides",
        "above",
        "below",
        "here",
        "there",
        "somewhere",
        "anywhere",
        "everywhere",
        "nowhere",
        "place", "places",
        "location", "locations",
        "position", "positions",
        "site", "sites",
        "spot", "spots",
        "region", "regions",
        "zone", "zones",
        "sector", "sectors",
        "territory", "territories",
        "space", "spaces",
        "room", "rooms",
        "time", "times",
        "period", "periods",
        "moment", "moments",
        "instant", "instants",
        "duration", "durations",
        "interval", "intervals",
        "span", "spans",
        "term", "terms",
        "era", "eras",
        "age", "ages",
        "epoch", "epochs",
        "cycle", "cycles",
        "round", "rounds",
        "turn", "turns",
        "series",
        "sequence", "sequences",
        "order", "orders",
        "class", "classes",
        "category", "categories",
        "group", "groups",
        "set", "sets",
        "collection", "collections",
        "array", "arrays",
        "list", "lists",
        "table", "tables",
        "chart", "charts",
        "graph", "graphs",
        "figure", "figures",
        "image", "images",
        "picture", "pictures",
        "photo", "photos",
        "photograph", "photographs",
        "illustration", "illustrations",
        "diagram", "diagrams",
        "scheme",
        "plot", "plots",
        "map", "maps",
        "representation", "representations",
        "display", "displays",
        "presentation", "presentations",
        "demonstration", "demonstrations",
        "exhibition", "exhibitions",
        "show", "shows",
        "event", "events",
        "activity", "activities",
        "action", "actions",
        "operation", "operations",
        "procedure", "procedures",
        "protocol", "protocols",
        "routine", "routines",
        "practice", "practices",
        "exercise", "exercises",
        "task", "tasks",
        "job", "jobs",
        "duty", "duties",
        "responsibility", "responsibilities",
        "assignment", "assignments",
        "project", "projects",
        "program", "programs",
        "programme", "programmes",
        "initiative", "initiatives",
        "effort", "efforts",
        "attempt", "attempts",
        "trial", "trials",
        "test", "tests",
        "examination", "examinations",
        "investigation", "investigations",
        "inquiry", "inquiries",
        "exploration", "explorations",
        "survey", "surveys",
        "review", "reviews",
        "assessment", "assessments",
        "evaluation", "evaluations",
        "measurement", "measurements",
        "determination", "determinations",
        "calculation", "calculations",
        "computation", "computations",
        "estimation", "estimations",
        "approximation", "approximations",
        "simulation", "simulations",
        "modeling", "modelings",
        "modelling", "modellings",
    ]

    /// Authors/investigators that should be filtered (handled by prompt but sometimes slip through).
    public static let authorTerms: Set<String> = [
        "author", "authors",
        "researcher", "researchers",
        "investigator", "investigators",
        "scientist", "scientists",
        "team", "teams",
        "group", "groups",
        "lab", "labs",
        "laboratory", "laboratories",
    ]

    // MARK: - Filtering

    /// Checks if a node string should be filtered out.
    ///
    /// - Parameter node: The node text to check.
    /// - Returns: `true` if the node should be removed.
    public static func shouldFilter(_ node: String) -> Bool {
        let normalized = node.lowercased().trimmingCharacters(in: .whitespacesAndNewlines)

        // Empty or very short
        if normalized.count < 2 {
            return true
        }

        // Direct match with stopwords
        if pronouns.contains(normalized) ||
           vagueNouns.contains(normalized) ||
           authorTerms.contains(normalized) {
            return true
        }

        // Check if it's just a pronoun with punctuation
        let stripped = normalized.filter { $0.isLetter || $0.isWhitespace }
        if pronouns.contains(stripped) {
            return true
        }

        return false
    }

    /// Filters an event, returning nil if any required node is filtered.
    ///
    /// - Parameter event: The hypergraph event to filter.
    /// - Returns: The filtered event with vague nodes removed, or nil if the event becomes invalid.
    public static func filter(_ event: Event) -> Event? {
        // Filter source nodes
        let filteredSources = event.source.filter { !shouldFilter($0) }
        if filteredSources.isEmpty {
            return nil
        }

        // Filter target nodes
        let filteredTargets = event.target.filter { !shouldFilter($0) }
        if filteredTargets.isEmpty {
            return nil
        }

        return Event(
            source: filteredSources,
            target: filteredTargets,
            relation: event.relation
        )
    }

    /// Filters a collection of events.
    ///
    /// - Parameter events: The events to filter.
    /// - Returns: Events with vague nodes removed.
    public static func filter(_ events: [Event]) -> [Event] {
        events.compactMap { filter($0) }
    }

    /// Filters a HypergraphJSON structure.
    ///
    /// - Parameter json: The hypergraph JSON to filter.
    /// - Returns: Filtered hypergraph JSON.
    public static func filter(_ json: HypergraphJSON) -> HypergraphJSON {
        HypergraphJSON(events: filter(json.events))
    }
}
